export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/intro.html.js"), meta: {"cover":"/assets/images/cover3.jpg","excerpt":"\n<p>将你的个人介绍和档案放置在此处。</p>\n","readingTime":{"minutes":0.08,"words":23},"title":"介绍页","icon":"circle-info","type":"article"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"博客主页","icon":"house"} }],
  ["/md/", { loader: () => import(/* webpackChunkName: "md_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.49,"words":1348},"title":"文档","icon":"laptop-code","type":"article"} }],
  ["/md/resume.html", { loader: () => import(/* webpackChunkName: "md_resume.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/resume.html.js"), meta: {"title":"个人简历","icon":"laptop-code","index":false} }],
  ["/md/code/", { loader: () => import(/* webpackChunkName: "md_code_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/code/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1350},"title":"代码笔记","icon":"laptop-code","type":"article"} }],
  ["/md/guide/", { loader: () => import(/* webpackChunkName: "md_guide_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/guide/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1350},"title":"教程手册","icon":"laptop-code","type":"article"} }],
  ["/md/project/", { loader: () => import(/* webpackChunkName: "md_project_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/project/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1349},"title":"项目库","icon":"laptop-code","type":"article"} }],
  ["/md/study/", { loader: () => import(/* webpackChunkName: "md_study_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/study/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1350},"title":"学习笔记","icon":"laptop-code","type":"article"} }],
  ["/md/code/java/", { loader: () => import(/* webpackChunkName: "md_code_java_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/code/java/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.49,"words":1347},"title":"Java","icon":"laptop-code","type":"article"} }],
  ["/md/guide/mygit/", { loader: () => import(/* webpackChunkName: "md_guide_mygit_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/guide/mygit/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1349},"title":"git教程","icon":"laptop-code","type":"article"} }],
  ["/md/project/market/", { loader: () => import(/* webpackChunkName: "md_project_market_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/project/market/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1351},"title":"大营销抽奖","icon":"laptop-code","type":"article"} }],
  ["/md/code/java/juc/dome.html", { loader: () => import(/* webpackChunkName: "md_code_java_juc_dome.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/code/java/juc/dome.html.js"), meta: {"category":["开发笔记","学习记录"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.96,"words":1489},"title":"Day1","icon":"laptop-code","index":false,"type":"article"} }],
  ["/md/code/java/juc/", { loader: () => import(/* webpackChunkName: "md_code_java_juc_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/code/java/juc/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.49,"words":1347},"title":"JUC","icon":"laptop-code","type":"article"} }],
  ["/md/guide/mygit/giteee/dome.html", { loader: () => import(/* webpackChunkName: "md_guide_mygit_giteee_dome.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/guide/mygit/giteee/dome.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1351},"title":"开发日志Guide","icon":"laptop-code","index":false,"type":"article"} }],
  ["/md/guide/mygit/giteee/", { loader: () => import(/* webpackChunkName: "md_guide_mygit_giteee_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/guide/mygit/giteee/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1349},"title":"Gitee码云","icon":"laptop-code","type":"article"} }],
  ["/md/project/market/bug/", { loader: () => import(/* webpackChunkName: "md_project_market_bug_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/project/market/bug/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1349},"title":"BUG笔记","icon":"laptop-code","type":"article"} }],
  ["/md/project/market/design/", { loader: () => import(/* webpackChunkName: "md_project_market_design_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/project/market/design/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1350},"title":"项目设计","icon":"laptop-code","type":"article"} }],
  ["/md/project/market/log/", { loader: () => import(/* webpackChunkName: "md_project_market_log_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/md/project/market/log/index.html.js"), meta: {"category":["自我介绍","专业技能","项目经验"],"excerpt":"<h2>任务</h2>\n<ul class=\"task-list-container\">\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-0\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-0\"> 环境配置</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-1\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-1\"> 搭建项目结构</label></li>\n<li class=\"task-list-item\"><input type=\"checkbox\" class=\"task-list-item-checkbox\" id=\"task-item-2\" checked=\"checked\" disabled=\"disabled\"><label class=\"task-list-item-label\" for=\"task-item-2\"> 跑通广播模式 RPC 过程调用</label></li>\n</ul>","readingTime":{"minutes":4.5,"words":1350},"title":"开发日志","icon":"laptop-code","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/%E8%87%AA%E6%88%91%E4%BB%8B%E7%BB%8D/", { loader: () => import(/* webpackChunkName: "category_自我介绍_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/category/自我介绍/index.html.js"), meta: {"title":"自我介绍 分类","index":false} }],
  ["/category/%E4%B8%93%E4%B8%9A%E6%8A%80%E8%83%BD/", { loader: () => import(/* webpackChunkName: "category_专业技能_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/category/专业技能/index.html.js"), meta: {"title":"专业技能 分类","index":false} }],
  ["/category/%E9%A1%B9%E7%9B%AE%E7%BB%8F%E9%AA%8C/", { loader: () => import(/* webpackChunkName: "category_项目经验_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/category/项目经验/index.html.js"), meta: {"title":"项目经验 分类","index":false} }],
  ["/category/%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0/", { loader: () => import(/* webpackChunkName: "category_开发笔记_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/category/开发笔记/index.html.js"), meta: {"title":"开发笔记 分类","index":false} }],
  ["/category/%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95/", { loader: () => import(/* webpackChunkName: "category_学习记录_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/category/学习记录/index.html.js"), meta: {"title":"学习记录 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"F:/gitObject/blog-theme-hope/blog/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
